version: '3.8'

services:
  firebook:
    image: maxjeffwell/firebook:nas
    container_name: firebook-app
    environment:
      - NODE_ENV=production
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 20s
      retries: 3
